services:
  db2:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pair2
      MYSQL_DATABASE: ArtistsAndWorks
      MYSQL_ROOT_HOST: '%'
    volumes:
      - aawdat2:/var/lib/mysql
    ports:
      - "53326:3306"
   phpmyadmin2:
	image: phpmyadmin/phpmyadmin:latest
	restart: always
	depends_on:
	-db2
	environment:
		PMA_HOST: db2
		PMA_USER: root
		PMA_PASSWORD: pair2
	ports:
	- "50082:80"

volumes:
  aawdat2:

